### ISSUE TITLE
CPU device leaks slang session.

### ISSUE THREAD

**Issue by csyonghe** [shader-slang/slang-rhi#53]
When slang-test uses cpu device, the slang session isn't properly released.

To reproduce, run `slang-test` with this arguments:
```
slang-test tests/compute/constant-buffer-memory-packing -api cpu
```

This currently triggers an assert in debug that the reference count of the slang session doesn't go to 0.

**Comment by skallweitNV** [comment]
Ok, this was actually caused by a change I made. Fixed now.
